---
title: "Build-Maps"
author: "Shawn Jassal"
date: "5/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(leaflet)
library(shiny)
library(geojsonio)
library(caret) # machine learning
library(broom)
library(plotROC)
```

```{r getData, message=FALSE, warning=FALSE}
# Data from: https://www.kaggle.com/sogun3/uspollution/downloads/uspollution.zip/1
csv_file <- "pollution_us_2000_2016.csv"
tidy_df <- read_csv(csv_file)
```

## 1.2 Tidy and Clean the Data

```{r tidyAndClean, warning=FALSE}
# Remove the columns: row number ("X1"), State Code, Country Code, Site Num, Address, and County
tidy_df <- tidy_df[-c(1:5,7)]

# Now delete all of the Units columns
# NO2 = parts per billion
# O3  = parts per million
# SO2 = parts per billion
# CO  = parts per million
tidy_df <- tidy_df[-c(5,10,15,20)]

# Remove the hour of the max value columns
tidy_df <- tidy_df[-c(4,8,12,16)]

# rename date column a DATE variable
colnames(tidy_df)[3] <- "Date"
tidy_df <- type_convert(tidy_df, col_types = cols("Date" = col_datetime("%Y-%m-%d")))

# Add a year column to speed up data visualization
tidy_df$year <- substring(tidy_df$Date,1,4)

# Add a month column
tidy_df$month <- substring(tidy_df$Date,6,7)
```

```{r longitudeLatitude, message=FALSE, warning=FALSE}
# Data from: https://simplemaps.com/data/us-cities
# Now get longitude and latitude of each locaiton
csv_file <- "uscitiesv1.5.csv"
cities_df <- read_csv(csv_file)
# Remove useless columns
cities_df <- cities_df[-c(2,3,5,6,9:16)] 
colnames(cities_df)[1] <- "City"
colnames(cities_df)[2] <- "State"

# Join the two table on City and State to get Longitude and latitude
tidy_df <- left_join(tidy_df, cities_df, by= c("City", "State"))

```

# 2. Exploratory Data Analysis

## 2.1 Interactive Maps
```{r mapPreprocessing, warning=FALSE}
# Create Icon
# Map Marker From: http://simpleicon.com/map-marker-2.html
myIcon <- makeIcon(
  iconUrl = "http://www.myiconfinder.com/uploads/iconsets/256-256-a5485b563efc4511e0cd8bd04ad0fe9e.png",
  iconWidth = 8, iconHeight = 9,
  iconAnchorX = 5, iconAnchorY = 5
)

# Create data frame with markers of all locations
markers_df <- tidy_df %>%
  distinct(City) %>%
  inner_join(select(tidy_df, City, lng, lat), by = "City") %>%
  distinct()

# Get From Here: https://github.com/PublicaMundi/MappingAPI/blob/master/data/geojson/us-states.json
# GitHub thread about the file: https://github.com/rstudio/leaflet/issues/498
states <- geojsonio::geojson_read("us-states.geojson", what = "sp")
# Create data frame with State names
states_name <- select(as.data.frame(states), name)
colnames(states_name)[1] <- "State"

# Create colors and palletes
bins <- c(0, 5, 10, 15, 20, 25, 30, 35, 40, Inf)
pal <- colorBin(palette="YlOrRd", domain = states$density, na.color = "000", bins = bins)
```

### 2.1.1 NO2 AQI Map

```{r mapNO2, warning=FALSE}
# Set to NO2 AQI at the year 2000
temp_df <- tidy_df %>%
  filter(year == 2000) %>%
  select(State, `NO2 AQI`) %>%
  group_by(State) %>%
  summarise(x = mean(`NO2 AQI`, na.rm = TRUE)) %>%
  right_join(states_name, by = "State")

colnames(temp_df)[2] <- "density"
# Set new density values
states$density <- temp_df$density

labels <- sprintf(
  "<strong>%s</strong><br/>%g AQI",
  states$name, states$density
) %>% lapply(htmltools::HTML)

ui <- fluidPage(
  leafletOutput("map"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("Year", "Year:", min = 2000, max = 2016, value = 2000,
                  animate = animationOptions(interval = 2000, loop = FALSE))
    ),
    mainPanel(
      tableOutput("Year")
    )
  )
)

server <- function(input, output, session){
  sliderValues <- reactive({
    data.frame(
      Name = c("Year"),
      Value = as.character(c(input$Year), stringsAsFactors = FALSE))
  })
  
  output$map <- renderLeaflet({
    map <- leaflet(states) %>%
      addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
      addPolygons(
        fillColor = ~pal(states$density),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto")) %>%
      addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                position = "bottomright") %>%
      addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
      setView(lat=39.508577, lng=-98.322468, zoom=4)
    
  })
  
  observe({ 
    # Set zoom and center map
    zoom <- reactive({
      ifelse(is.null(input$map01_zoom),4,input$map01_zoom)
    })
    center <- reactive({
      if(is.null(input$map01_center)){
        return(c(39.508577, -98.322468))
      }else{
        return(input$map01_center)
      }
    })
    
    # Get new data based off of year value
    temp_df <- tidy_df %>%
      filter(year == input$Year) %>%
      select(State, `NO2 AQI`) %>%
      group_by(State) %>%
      summarise(x = mean(`NO2 AQI`,na.rm = TRUE)) %>%
      right_join(states_name, by = "State")
    colnames(temp_df)[2] <- "density"
    # Set new density values
    states$density <- temp_df$density
    
    # Update the map
    output$map <- renderLeaflet({
      map <- leaflet(states) %>%
        addProviderTiles("MapBox", options = providerTileOptions(
          id = "mapbox.light",
          accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
        addPolygons(
          fillColor = ~pal(states$density),
          weight = 2,
          opacity = 1,
          color = "white",
          dashArray = "3",
          fillOpacity = 0.7,
          highlight = highlightOptions(
            weight = 5,
            color = "#666",
            dashArray = "",
            fillOpacity = 0.7,
            bringToFront = TRUE),
          label = labels,
          labelOptions = labelOptions(
            style = list("font-weight" = "normal", padding = "3px 8px"),
            textsize = "15px",
            direction = "auto")) %>%
        addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                  position = "bottomright") %>%
        addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
        setView(lat=center()[1], lng=center()[2], zoom=zoom())
      
    })
    
  })
  
}
# Run shiny
shinyApp(ui, server)

```

### 2.1.2 O3 AQI Map
```{r mapO3, echo=FALSE, warning=FALSE}
# Set to O3 AQI at the year 2000
temp_df <- tidy_df %>%
  filter(year == 2000) %>%
  select(State, `O3 AQI`) %>%
  group_by(State) %>%
  summarise(x = mean(`O3 AQI`, na.rm = TRUE)) %>%
  right_join(states_name, by = "State")

colnames(temp_df)[2] <- "density"
# Set new density values
states$density <- temp_df$density

labels <- sprintf(
  "<strong>%s</strong><br/>%g AQI",
  states$name, states$density
) %>% lapply(htmltools::HTML)

ui <- fluidPage(
  leafletOutput("map"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("Year", "Year:", min = 2000, max = 2016, value = 2000,
                  animate = animationOptions(interval = 2000, loop = FALSE))
    ),
    mainPanel(
      tableOutput("Year")
    )
  )
)

server <- function(input, output, session){
  sliderValues <- reactive({
    data.frame(
      Name = c("Year"),
      Value = as.character(c(input$Year), stringsAsFactors = FALSE))
  })
  
  output$map <- renderLeaflet({
    map <- leaflet(states) %>%
      addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
      addPolygons(
        fillColor = ~pal(states$density),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto")) %>%
      addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                position = "bottomright") %>%
      addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
      setView(lat=39.508577, lng=-98.322468, zoom=4)
    
  })
  
  observe({ 
    # Set zoom and center map
    zoom <- reactive({
      ifelse(is.null(input$map01_zoom),4,input$map01_zoom)
    })
    center <- reactive({
      if(is.null(input$map01_center)){
        return(c(39.508577, -98.322468))
      }else{
        return(input$map01_center)
      }
    })
    
    # Get new data based off of year value
    temp_df <- tidy_df %>%
      filter(year == input$Year) %>%
      select(State, `O3 AQI`) %>%
      group_by(State) %>%
      summarise(x = mean(`O3 AQI`,na.rm = TRUE)) %>%
      right_join(states_name, by = "State")
    colnames(temp_df)[2] <- "density"
    # Set new density values
    states$density <- temp_df$density
    
    # Update the map
    output$map <- renderLeaflet({
      map <- leaflet(states) %>%
        addProviderTiles("MapBox", options = providerTileOptions(
          id = "mapbox.light",
          accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
        addPolygons(
          fillColor = ~pal(states$density),
          weight = 2,
          opacity = 1,
          color = "white",
          dashArray = "3",
          fillOpacity = 0.7,
          highlight = highlightOptions(
            weight = 5,
            color = "#666",
            dashArray = "",
            fillOpacity = 0.7,
            bringToFront = TRUE),
          label = labels,
          labelOptions = labelOptions(
            style = list("font-weight" = "normal", padding = "3px 8px"),
            textsize = "15px",
            direction = "auto")) %>%
        addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                  position = "bottomright") %>%
        addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
        setView(lat=center()[1], lng=center()[2], zoom=zoom())
      
    })
    
  })
  
}
# Run shiny
shinyApp(ui, server)

```

### 2.1.3 SO2 AQI Map
```{r mapSO2, echo=FALSE, warning=FALSE}
# Set to SO2 AQI at the year 2000
temp_df <- tidy_df %>%
  filter(year == 2000) %>%
  select(State, `SO2 AQI`) %>%
  group_by(State) %>%
  summarise(x = mean(`SO2 AQI`, na.rm = TRUE)) %>%
  right_join(states_name, by = "State")

colnames(temp_df)[2] <- "density"
# Set new density values
states$density <- temp_df$density

labels <- sprintf(
  "<strong>%s</strong><br/>%g AQI",
  states$name, states$density
) %>% lapply(htmltools::HTML)

ui <- fluidPage(
  leafletOutput("map"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("Year", "Year:", min = 2000, max = 2016, value = 2000,
                  animate = animationOptions(interval = 2000, loop = FALSE))
    ),
    mainPanel(
      tableOutput("Year")
    )
  )
)

server <- function(input, output, session){
  sliderValues <- reactive({
    data.frame(
      Name = c("Year"),
      Value = as.character(c(input$Year), stringsAsFactors = FALSE))
  })
  
  output$map <- renderLeaflet({
    map <- leaflet(states) %>%
      addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
      addPolygons(
        fillColor = ~pal(states$density),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto")) %>%
      addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                position = "bottomright") %>%
      addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
      setView(lat=39.508577, lng=-98.322468, zoom=4)
    
  })
  
  observe({ 
    # Set zoom and center map
    zoom <- reactive({
      ifelse(is.null(input$map01_zoom),4,input$map01_zoom)
    })
    center <- reactive({
      if(is.null(input$map01_center)){
        return(c(39.508577, -98.322468))
      }else{
        return(input$map01_center)
      }
    })
    
    # Get new data based off of year value
    temp_df <- tidy_df %>%
      filter(year == input$Year) %>%
      select(State, `SO2 AQI`) %>%
      group_by(State) %>%
      summarise(x = mean(`SO2 AQI`,na.rm = TRUE)) %>%
      right_join(states_name, by = "State")
    colnames(temp_df)[2] <- "density"
    # Set new density values
    states$density <- temp_df$density
    
    # Update the map
    output$map <- renderLeaflet({
      map <- leaflet(states) %>%
        addProviderTiles("MapBox", options = providerTileOptions(
          id = "mapbox.light",
          accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
        addPolygons(
          fillColor = ~pal(states$density),
          weight = 2,
          opacity = 1,
          color = "white",
          dashArray = "3",
          fillOpacity = 0.7,
          highlight = highlightOptions(
            weight = 5,
            color = "#666",
            dashArray = "",
            fillOpacity = 0.7,
            bringToFront = TRUE),
          label = labels,
          labelOptions = labelOptions(
            style = list("font-weight" = "normal", padding = "3px 8px"),
            textsize = "15px",
            direction = "auto")) %>%
        addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                  position = "bottomright") %>%
        addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
        setView(lat=center()[1], lng=center()[2], zoom=zoom())
      
    })
    
  })
}
# Run shiny
shinyApp(ui, server)
```

### 2.1.4 CO AQI Map
```{r mapCO, echo=FALSE, warning=FALSE}
# Set to CO AQI at the year 2000
temp_df <- tidy_df %>%
  filter(year == 2000) %>%
  select(State, `CO AQI`) %>%
  group_by(State) %>%
  summarise(x = mean(`CO AQI`, na.rm = TRUE)) %>%
  right_join(states_name, by = "State")

colnames(temp_df)[2] <- "density"
# Set new density values
states$density <- temp_df$density

labels <- sprintf(
  "<strong>%s</strong><br/>%g AQI",
  states$name, states$density
) %>% lapply(htmltools::HTML)

ui <- fluidPage(
  leafletOutput("map"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("Year", "Year:", min = 2000, max = 2016, value = 2000,
                  animate = animationOptions(interval = 2000, loop = FALSE))
    ),
    mainPanel(
      tableOutput("Year")
    )
  )
)

server <- function(input, output, session){
  sliderValues <- reactive({
    data.frame(
      Name = c("Year"),
      Value = as.character(c(input$Year), stringsAsFactors = FALSE))
  })
  
  output$map <- renderLeaflet({
    map <- leaflet(states) %>%
      addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
      addPolygons(
        fillColor = ~pal(states$density),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto")) %>%
      addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                position = "bottomright") %>%
      addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
      setView(lat=39.508577, lng=-98.322468, zoom=4)
    
  })
  
  observe({ 
    # Set zoom and center map
    zoom <- reactive({
      ifelse(is.null(input$map01_zoom),4,input$map01_zoom)
    })
    center <- reactive({
      if(is.null(input$map01_center)){
        return(c(39.508577, -98.322468))
      }else{
        return(input$map01_center)
      }
    })
    
    # Get new data based off of year value
    temp_df <- tidy_df %>%
      filter(year == input$Year) %>%
      select(State, `CO AQI`) %>%
      group_by(State) %>%
      summarise(x = mean(`CO AQI`,na.rm = TRUE)) %>%
      right_join(states_name, by = "State")
    colnames(temp_df)[2] <- "density"
    # Set new density values
    states$density <- temp_df$density
    
    # Update the map
    output$map <- renderLeaflet({
      map <- leaflet(states) %>%
        addProviderTiles("MapBox", options = providerTileOptions(
          id = "mapbox.light",
          accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>%
        addPolygons(
          fillColor = ~pal(states$density),
          weight = 2,
          opacity = 1,
          color = "white",
          dashArray = "3",
          fillOpacity = 0.7,
          highlight = highlightOptions(
            weight = 5,
            color = "#666",
            dashArray = "",
            fillOpacity = 0.7,
            bringToFront = TRUE),
          label = labels,
          labelOptions = labelOptions(
            style = list("font-weight" = "normal", padding = "3px 8px"),
            textsize = "15px",
            direction = "auto")) %>%
        addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
                  position = "bottomright") %>%
        addMarkers(markers_df$lng, markers_df$lat, popup = markers_df$City, icon = myIcon) %>%
        setView(lat=center()[1], lng=center()[2], zoom=zoom())
      
    })
    
  })
  
}
# Run shiny
shinyApp(ui, server)
```